branches:
  - main
tagFormat: "${version}"
plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: refactor
          release: patch
  - - "@semantic-release/release-notes-generator"
    - parserOpts:
        noteKeywords: ["BREAKING CHANGE", "BREAKING CHANGES", "BREAKING"]
      preset: conventionalcommits
      presetConfig:
        types:
          - type: build
            section: Build System
            hidden: false
          - type: chore
            section: Build System
            hidden: false
          - type: ci
            section: Continuous Integration
            hidden: false
          - type: docs
            section: Documentation
            hidden: false
          - type: feat
            section: Features
            hidden: false
          - type: fix
            section: Bug Fixes
            hidden: false
          - type: perf
            section: Performance Improvements
            hidden: false
          - type: refactor
            section: Code Refactoring
            hidden: false
          - type: style
            section: Styles
            hidden: false
          - type: test
            section: Tests
            hidden: false
      writerOpts:
        commitSort: ["subject", "scope"]
  - - "@semantic-release/changelog"
    - changelogTitle: JRuby OpenHAB Scripting Change Log
      changelogFile: CHANGELOG.md
  - - semantic-release-rubygem
    - gemFileDir: pkg/
      updateGemfileLock: true
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - lib/openhab/version.rb
        - Gemfile.lock
  - - "@semantic-release/github"
    - assets:
        - path: "./pkg/openhab-scripting-${nextRelease.version}.gem"
          label: openhab-scripting Ruby Gem
