require:
  - rubocop-performance
  - rubocop-rake

inherit_mode:
  merge:
    - Exclude # we want our Exclude to build on the excludes from the default config

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - bin/*

# enforced by checking for 100% documented from `yard --stats`
# RuboCop doesn't know if a module is documented in a different file
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  UseHashRocketsWithSymbolValues: true
Gemspec/RequireMFA:
  Enabled: false

# The following is excluded because it is within the shipped Gem
# the cop is searching for the gem itself, so exclude this file
Bundler/GemFilename:
  Exclude:
    - lib/openhab/dsl/gems.rb
