require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude # we want our Exclude to build on the excludes from the default config

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - bin/*

# The following is excluded because it is within the shipped Gem
# the cop is searching for the gem itself, so exclude this file
Bundler/GemFilename:
  Exclude:
    - lib/openhab/dsl/gems.rb

Layout/LineLength:
  IgnoredPatterns:
    - "# @example" # YARD example titles can't be broken up onto multiple lines.
    - "# @see" # YARD example titles can't be broken up onto multiple lines.
    - "data:[a-z/]+;base64," # Base64 data is long

Lint/RescueException:
  Enabled: false # we need to rescue Java exceptions quite a bit
Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - spec/openhab/core/types/*_spec.rb

Metrics:
  Enabled: false

Performance/Casecmp:
  AutoCorrect: false

RSpec/DescribeClass:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExpectActual:
  Exclude:
    - spec/openhab/core/types/*_spec.rb
RSpec/FilePath:
  CustomTransform:
    OpenHAB: openhab
RSpec/IdenticalEqualityAssertion:
  Exclude:
    - spec/openhab/core/types/*_spec.rb
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/CaseEquality:
  Exclude: # we're explicitly testing this operator
  - spec/openhab/core/types/*_spec.rb
# enforced by checking for 100% documented from `yard --stats`
# RuboCop doesn't know if a module is documented in a different file
Style/Documentation:
  Enabled: false
Style/GlobalVars:
  AllowedVariables: # these globals are set by OpenHAB, and we can't change their name
   - $actions
   - $events
   - $ir
   - $rules
   - $se
   - $scriptExtension
   - $things
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
Style/PercentQLiterals:
  EnforcedStyle: upper_case_q
Style/PerlBackrefs:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/SpecialGlobalVars:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
Style/YodaCondition:
  Exclude:
    - spec/openhab/core/types/*_spec.rb
