require:
  - rubocop-performance
  - rubocop-rake

inherit_mode:
  merge:
    - Exclude # we want our Exclude to build on the excludes from the default config

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - bin/*

Style/HashSyntax:
  UseHashRocketsWithSymbolValues: true

# The following is excluded because it is within the shipped Gem
# the cop is searching for the gem itself, so exclude this file
Bundler/GemFilename:
  Exclude:
    - lib/openhab/dsl/gems.rb 
