require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude # we want our Exclude to build on the excludes from the default config

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - bin/*

RSpec/DescribeClass:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/FilePath:
  CustomTransform:
    OpenHAB: openhab
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

Style/CaseEquality:
  Exclude: # we're explicitly testing this operator
  - spec/openhab/dsl/types/*_spec.rb
# enforced by checking for 100% documented from `yard --stats`
# RuboCop doesn't know if a module is documented in a different file
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  UseHashRocketsWithSymbolValues: true
Style/GlobalVars:
  AllowedVariables: # these globals are set by OpenHAB, and we can't change their name
   - $actions
   - $ir
   - $rules
   - $se
   - $scriptExtension
   - $things

Gemspec/RequireMFA:
  Enabled: false

# The following is excluded because it is within the shipped Gem
# the cop is searching for the gem itself, so exclude this file
Bundler/GemFilename:
  Exclude:
    - lib/openhab/dsl/gems.rb
