name: Deploy YARD docs to Pages

on:
  push:
    branches: ["main"]
    tags: ["v*"]

env:
  RUBY_VERSION: 3.1.3

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Build YARD docs
        run: bin/yardoc
      - name: Determine Destination Dir
        id: destination_dir
        run: ruby -e 'ref_name = "${{ github.ref_name }}"; ref_name = ref_name[1..-1].split(".")[0..1].join(".") if "${{ github.ref_type }}" == "tag"; puts "DESTINATION_DIR=#{ref_name}"' >> $GITHUB_OUTPUT
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/yard/
          destination_dir: ${{ steps.destination_dir.outputs.DESTINATION_DIR }}
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
